<?php

namespace RR\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function findLastCommentResto($id_resto,$id_user)
    {
        $query = $this
            ->createQueryBuilder('c')
            ->select('c')
            ->where('c.user = :id_user')

            ->andWhere('c.restaurant = :id_resto')

            ->andWhere('DATE_DIFF(c.date,CURRENT_DATE())=0') //recup les commentaires du jour
            ->setParameter('id_user', $id_user)
            ->setParameter('id_resto', $id_resto);


        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}