<?php

namespace RR\CoreBundle\Entity;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * SiteContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTypeContent($type)
    {
        $query = $this->createQueryBuilder('sc')
            ->select('sc')
            ->leftJoin('sc.image','img')
            ->addSelect('img');
        $query->where('sc.typeContent = :type')
            ->setParameter('type', $type)
            ->andWhere('sc.enabled = true')
            ->orderBy('sc.id')
        ;
        return $query
            ->getQuery()
            ->getResult()
            ;
    }
}
