imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1']
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    trusted_proxies: ['127.0.0.1']

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            # other form themes
            - 'VichUploaderBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                 acos: DoctrineExtensions\Query\Mysql\Acos
                 asin: DoctrineExtensions\Query\Mysql\Asin
                 atan2: DoctrineExtensions\Query\Mysql\Atan2
                 atan: DoctrineExtensions\Query\Mysql\Atan
                 ceil: DoctrineExtensions\Query\Mysql\Ceil
                 cos: DoctrineExtensions\Query\Mysql\Cos
                 cot: DoctrineExtensions\Query\Mysql\Cot
                 floor: DoctrineExtensions\Query\Mysql\Floor
                 hour: DoctrineExtensions\Query\Mysql\Hour
                 pi: DoctrineExtensions\Query\Mysql\Pi
                 power: DoctrineExtensions\Query\Mysql\Power
                 quarter: DoctrineExtensions\Query\Mysql\Quarter
                 radians: DoctrineExtensions\Query\Mysql\Radians
                 rand: DoctrineExtensions\Query\Mysql\Rand
                 round: DoctrineExtensions\Query\Mysql\Round
                 sin: DoctrineExtensions\Query\Mysql\Sin
                 std: DoctrineExtensions\Query\Mysql\Std
                 tan: DoctrineExtensions\Query\Mysql\Tan


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: RR\UserBundle\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: rruserbundle_user_registration
        confirmation:
            enabled: true
            from_email:
                address:       noreply.resto@gmail.com
                sender_name:   Enregistrement RestoRegimes


bazinga_geocoder:
    default_provider:         google_maps
    providers:
        google_maps:
            locale:               null
            region:               null
            use_ssl:              false
            api_key:              null

ivory_google_map:
    map:


        # Prefix used for the generation of the map javascript variable
        prefix_javascript_variable: "map_"

        # HTML container ID used for the map container
        html_container: "map_canvas"

        # If this flag is enabled, the map will load asynchronous
        async: false

        # If this flag is enabled, the map will autozoom on the overlays added
        auto_zoom: false

        # Center coordinate of the map
        # If the autozoom flag is enabled, the center is not used
        center:
            longitude: 48.8548780
            latitude: 2.3464432
            no_wrap: true

        # Zoom of the map
        # If the autozoom flag is enabled, the zoom is not used
        zoom: 16

        # Default map type
        # Available map type : hybrid, roadmap, satellite, terrain
        type: "roadmap"

        # Map width
        width: "100%"

        # Map height
        height: "450px"

        # Custom map options
        # By default, there is no map options
        map_options:
            disableDefaultUI: false
            disableDoubleClickZoom: false

        # Custom stylesheet options
        # By default, there is no stylesheet options except width & height
        stylesheet_options:
            border: "2px solid #dadada"
            background-color: "#ffffff"

        # google map Api language, default en
        language: fr



# app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        resto_image:
            uri_prefix:         /images/resto
            upload_destination: %kernel.root_dir%/../web/images/resto
            namer:              vich_uploader.namer_origname
            directory_namer:    my.directory_namer.resto

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        user_image:
            uri_prefix:         /images/user
            upload_destination: %kernel.root_dir%/../web/images/user
            namer:              vich_uploader.namer_origname
            directory_namer:    my.directory_namer.user

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        site_image:
            uri_prefix:         /images/site
            upload_destination: %kernel.root_dir%/../web/images/site
            namer:              vich_uploader.namer_origname
            directory_namer:    my.directory_namer.site_image

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

ewz_recaptcha:
    public_key:  6LePWhQTAAAAAEw7Djrf-tTiqLOdvfjugaiEd72l
    private_key: 6LePWhQTAAAAADpkSZeAj2BWj6CD3iU9C5iIi4Dc
    locale_key:  %kernel.default_locale%
