fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rr_user:
    resource: "@RRUserBundle/Resources/config/routing.yml"

rr_restaurant:
    resource: "@RRRestaurantBundle/Resources/config/routing.yml"
    prefix:   /Restaurant

rr_core:
    resource: "@RRCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:

    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:

    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

    prefix: /profile


fos_user_register:

    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

    prefix: /register


fos_user_resetting:

    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

    prefix: /resetting


fos_user_change_password:

    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

    prefix: /change_password

fos_user_group:

    resource: "@FOSUserBundle/Resources/config/routing/group.xml"

    prefix: /group

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

google_login:
    pattern: /login/google