security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PRO, ROLE_ADMIN]
        ROLE_PRO:         [ROLE_USER, ROLE_PRO]
        ROLE_USER:        [ROLE_USER]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle,in_memory]
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    pro:
                        password: pro
                        roles: 'ROLE_PRO'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:        ^/
            provider: chain_provider
            anonymous:      true
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    service: my_user_provider
            form_login:
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        "%secret%"
            access_denied_url: fos_user_security_login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Restaurant/admin, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/Restaurant/pro, role: ROLE_PRO }
        - { path: ^/pro/, role: ROLE_PRO }
        - { path: ^/user, role: ROLE_USER }