# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    core_helper.class: RR\CoreBundle\Services\CoreHelper
    site_image_directory_namer.class: RR\CoreBundle\Services\SiteImageDirectoryNamer
    user_directory_namer.class: RR\UserBundle\Services\UsernameDirectoryNamer
    resto_directory_namer.class: RR\RestaurantBundle\Services\RestaurantDirectoryNamer


services:
  core_helper:
    class:  %core_helper.class%
    arguments: [ @router ]

  my.directory_namer.user:
      class:  %user_directory_namer.class%

  my.directory_namer.resto:
        class:  %resto_directory_namer.class%

  my.directory_namer.site_image:
          class:  %site_image_directory_namer.class%

  rruserbundle.registration.form.type:
          class: RR\UserBundle\Form\RegistrationType
          arguments: [%fos_user.model.user.class%]
          tags:
              - { name: form.type, alias: rruserbundle_user_registration }
