<?php

namespace RR\RestaurantBundle\Entity;

/**
 * RegimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimeRepository extends \Doctrine\ORM\EntityRepository
{
}
