<?php

namespace RR\RestaurantBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestoImageRepository extends \Doctrine\ORM\EntityRepository
{

}
