rr_core_homepage:
    path:     /
    defaults: { _controller: RRCoreBundle:Default:index }

rr_core_search:
    path:     /recherche/{page}
    defaults: { _controller: RRCoreBundle:Default:recherche, page: 1}
    requirements:
            page: \d*
