rr_core_homepage:
    path:     /
    defaults: { _controller: RRCoreBundle:Default:index }

rr_core_search:
    path:     /recherche
    defaults: { _controller: RRCoreBundle:Default:recherche}

rr_core_favori_add:
    path:     /favori/add/{id_resto}
    defaults: { _controller: RRCoreBundle:Default:addfavori}

rr_core_favori_remove:
    path:     /favori/remove/{id_resto}
    defaults: { _controller: RRCoreBundle:Default:removefavori}

rr_core_commentaire_add:
    path:     /commentaire/add/{id_resto}
    defaults: { _controller: RRCoreBundle:Default:addcommentaire}

rr_core_faq:
    path: /faq
    defaults: { _controller:RRCoreBundle:Default:faq}

rr_core_mentions:
    path: /mentions
    defaults: { _controller:RRCoreBundle:Default:mentions}

rr_core_cgu:
    path: /cgu
    defaults: { _controller:RRCoreBundle:Default:cgu}

rr_core_maintenance:
    path: /maint_on/{action}
    defaults: { _controller:RRCoreBundle:Default:setMaintennance }
