rr_data_homepage:
    path:     /places
    defaults: { _controller: RRDataBundle:Default:index }

rr_data_search:
    path:     /places_search
    defaults: { _controller: RRDataBundle:Default:search }
