rr_restaurant_home:
    path:    /admin/{page}
    defaults: { _controller: RRRestaurantBundle:Restaurant:index, page: 1 }
    requirements:
        page: \d*

rr_restaurant_view:
    path:    /{id}
    defaults: { _controller: RRRestaurantBundle:Restaurant:view }
    requirements:
            id: \d+

rr_restaurant_add:
    path:    /pro/add
    defaults: { _controller: RRRestaurantBundle:Restaurant:add }

rr_restaurant_horaires:
    path:    /pro/horaires/{id}
    defaults: { _controller: RRRestaurantBundle:Restaurant:horaires }
    requirements:
        id: \d+

rr_restaurant_images:
    path:    /pro/images/{id}
    defaults: { _controller: RRRestaurantBundle:Restaurant:images }
    requirements:
            id: \d+

rr_restaurant_edit:
    path:    /pro/edit/{id}
    defaults: { _controller: RRRestaurantBundle:Restaurant:edit }
    requirements:
        id: \d+

rr_restaurant_delete:
    path:    /pro/delete/{id}
    defaults: { _controller: RRRestaurantBundle:Restaurant:delete }
    requirements:
        id: \d+
