services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    rr_restaurant.antispam:
        class: RR\RestaurantBundle\Antispam\RRAntispam
        arguments: [@mailer, %locale%, 50]

    rr_restaurant.doctrine.notification:
            class: RR\RestaurantBundle\DoctrineListener\ApplicationNotification
            arguments: [@mailer]
            tags:
                - { name: doctrine.event_listener, event: postPersist }